[entryPoints]
  [entryPoints.web]
    address = ":80"

# traefik dashboard over http
[api]
insecure = true

[log]
level = "INFO"

[ping]

[accessLog]
# containers are not discovered automatically
[providers]
  [providers.docker]
    exposedByDefault = false